apiVersion: apps/v1
kind: Deployment
metadata:
  name: assign2flask
  labels:
    app: assign2flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: assign2flask
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: assign2flask
    spec:
      containers:
        - name: assign2flask
          image: changpeng3336/assign2:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /about
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 3
